services:
  api-gateway:
    build:
      context: ../infrastructure/api-gateway
    container_name: api-gateway-mt-platform
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    environment:
      PORT: ${GATEWAY_PORT}
      MANAGEMENT_PORT: ${MANAGEMENT_PORT}
      SESSION_SECURE: ${SESSION_SECURE}
      RD_HOST: ${RD_HOST}
      RD_PORT: ${RD_PORT}
      RD_PASSWORD: ${RD_PASSWORD}

      KC_CLIENT_ID: ${KC_GATEWAY_CLIENT_ID}
      KC_CLIENT_SECRET: ${KC_GATEWAY_CLIENT_SECRET}
      KC_PUBLIC_BASE_URL: ${KC_PUBLIC_BASE_URL}
      KC_INTERNAL_BASE_URL: ${KC_INTERNAL_BASE_URL}
      KC_REALM: ${KC_REALM}

      FRONTEND_URL: ${FRONTEND_URL}
      TRANSACTION_SERVICE_PORT: ${TRANSACTION_SERVICE_PORT}
      WALLET_SERVICE_PORT: ${WALLET_SERVICE_PORT}
    networks:
      - money-transfer-net
    depends_on:
      redis:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    restart: unless-stopped