server:
  port: ${PORT}

spring:
  application:
    name: wallet-service

  datasource:
    hikari:
      pool-name: HikariPool-wallet
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    database: postgresql

  flyway:
    validate-on-migrate: true